# Generated by Django 5.2.3 on 2025-06-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='content',
            unique_together={('title', 'author')},
        ),
    ]
